name: CI/CD CodePipeline Release Changes & CloudFront Invalidation

on:

  push:

    branches: [main]

env:
  BUCKET_NAME : "team11degrees.com"

  AWS_REGION : "eu-west-1"

  AWS_CLOUDFRONT : "E2QYRM5SBMAO5P"
# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT

  contents: read    # This is required for actions/checkout

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Configure AWS Credentials

        uses: aws-actions/configure-aws-credentials@v1

        with:

          role-to-assume: arn:aws:iam::194104352727:role/github-actions-role

          role-session-name: github-actions-role

          aws-region: ${{ env.AWS_REGION }}

          # aws-access-key-id: ${{ secrets.AWS_KEY }}

          # aws-secret-access-key: ${{ secrets.AWS_SECRET }}

          # aws-region: ${{ secrets.AWS_REGION }}

      - name: Release CodePipeline

        run: aws codepipeline start-pipeline-execution --name team11degrees.com

      - name: Invalidate cache

        # run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/*"

        run: aws cloudfront create-invalidation --distribution-id ${{ env.AWS_CLOUDFRONT }} --paths "/*"
