# This is a basic workflow to help you get started with Actions
name: Trigger AWS CodePipeline
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    steps:
      - name: Trigger AWS CodePipeline
        uses: zulhfreelancer/aws-codepipeline-action@v1
        with:
          aws-region: "eu-west-1"
          aws-access-key: ${{ secrets.AWS_KEY }}
          aws-secret-key: ${{ secrets.AWS_SECRET }}
          pipeline-name: "team11degrees.com"          